[package]
name = "bitswap"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[build-dependencies]
prost-build = "0.6.1"

[dependencies]
anyhow = "1.0.28"
async-std = "1.5.0"
async-trait = "0.1.29"
fnv = "1.0.6"
futures = "0.3.4"
libipld = "0.1.0"
libp2p-core = "0.19.2"
libp2p-swarm = "0.19.1"
log = "0.4.8"
multihash = "0.10.1"
prost = "0.6.1"
thiserror = "1.0.14"
unsigned-varint = "0.3.2"
